name: Build and release kernel object 

on: 
    push:
            branches:  [cap-to-patch]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - name: build dockerfile
              run: docker build -t builder .
            - name: compile
              run: docker run --rm --volume ${GITHUB_WORKSPACE}/:/linux:Z builder
            - name: release
              uses: ncipollo/release-action@v1
              with:
                  artifacts: /driver/misc/rm-pogo/pogo.ko
                  commit: cap-to-patch
                  tag: patch
